### ISSUE TITLE
Can this be adapted to work with other hmrc projects?

### ISSUE THREAD

**Issue by hicnar** [hmrc/sm2#44]
Hi,

I myself am an EE associate, MTD "veteran" from a few years back, currently on a gig in another HMRC team. I remember sm as a quite useful and capable tool and we have a similar situation there, basically more and more micro services exchanging data with one another and I was thinking whether it would make sense to try to adapt sm2 to our needs. 
Obviously there are some differences for instance we use a different artifactory, services are written with Java and Spring Boot stack etc. Whoever maintains that please let me know whether it would be feasible to adapt it.

**Comment by christopherjturner** [comment]
Hey @hicnar 
It should be fairly straightforward to adapt, it currently runs java based services as well as scala ones but is slightly opinionated about how they're packaged and started.

A few things that might need to add/change:
- Overriding the artifactory url (doable via config.json in the config repo)
- Supporting non tar/gz artifacts (if required)
- Support more flexible artifact naming schemes/version numbers (if required)
- A more flexible start service, it currently hard-codes the start command to be ./$servicename/bin/$servicename  https://github.com/hmrc/sm2/blob/main/servicemanager/startservice.go#L154 
- Add/remove some of the hard coded checks (mongo/vpn check)
- Start from source is very scala/sbt specific and would need to be expanded to support other languages
- It assumes services can be configured via command line args
- Currently doesn't work on windows outside of WSL (though platform.go could be extended to support this)

Otherwise it might not be that hard to do. Feel free to fork the project and/or raise PRs!
